### ISSUE TITLE
Crashes ILSpy 3.0.1

### ISSUE THREAD

**Issue by iliakonnov** [sailro/Reflexil#117]
ILSpy release: https://github.com/icsharpcode/ILSpy/releases/tag/v3.0.1
Reflexil both nightly version (https://ci.appveyor.com/project/sailro/reflexil/build/Build%2074/artifacts) and stable (https://github.com/sailro/Reflexil/releases/tag/v2.1). AIO crashes same as normal vesrsion.
```
---------------------------
Sorry, we crashed
---------------------------
System.Windows.Markup.XamlParseException: The invocation of the constructor on type 'ICSharpCode.ILSpy.MainWindow' that matches the specified binding constraints threw an exception. ---> System.ComponentModel.Composition.CompositionException: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.



1) Could not load file or assembly 'Mono.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)



Resulting in: Could not load file or assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)



Resulting in: An exception occurred while trying to create an instance of type 'Reflexil.Plugins.ILSpy.ILSpyPackage'.



Resulting in: Cannot activate part 'Reflexil.Plugins.ILSpy.ILSpyPackage'.

Element: Reflexil.Plugins.ILSpy.ILSpyPackage -->  Reflexil.Plugins.ILSpy.ILSpyPackage -->  AssemblyCatalog (Assembly="Reflexil.ILSpy.Plugin, Version=2.2.0.0, Culture=neutral, PublicKeyToken=b086ee4e8cc6c7d7")



Resulting in: Cannot get export 'Reflexil.Plugins.ILSpy.ILSpyPackage (ContractName="MainMenuCommand")' from part 'Reflexil.Plugins.ILSpy.ILSpyPackage'.

Element: Reflexil.Plugins.ILSpy.ILSpyPackage (ContractName="MainMenuCommand") -->  Reflexil.Plugins.ILSpy.ILSpyPackage -->  AssemblyCatalog (Assembly="Reflexil.ILSpy.Plugin, Version=2.2.0.0, Culture=neutral, PublicKeyToken=b086ee4e8cc6c7d7")



   at System.ComponentModel.Composition.Hosting.CompositionServices.GetExportedValueFromComposedPart(ImportEngine engine, ComposablePart part, ExportDefinition definition)

   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportedValue(CatalogPart part, ExportDefinition export, Boolean isSharedPart)

   at System.ComponentModel.Composition.Primitives.Export.get_Value()

   at System.ComponentModel.Composition.ExportServices.GetCastedExportedValue[T](Export export)

   at System.Lazy`1.CreateValue()

   at System.Lazy`1.LazyInitValue()

   at ICSharpCode.ILSpy.MainWindow.InitMainMenu()

   at ICSharpCode.ILSpy.MainWindow..ctor()

   --- End of inner exception stack trace ---

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)

   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)

   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)

   at System.Windows.Application.DoStartup()

   at System.Windows.Application.<.ctor>b__1_0(Object unused)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

```

**Comment by viktorvesely** [comment]
Use earlier version of IlSpy

**Comment by sailro** [comment]
Closing, this is related to https://github.com/sailro/Reflexil/issues/116
