### ISSUE TITLE
Object reference not set to an instance of an object - Edit custom attribute

### ISSUE THREAD

**Issue by tgowans** [sailro/Reflexil#33]
When trying to update changes made to a custom attribute the below is thrown:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Reflexil.Utils.CecilHelper.GetModuleFromCustomAttributeProvider(ICustomAttributeProvider provider)
   at Reflexil.Forms.CustomAttributeForm.FixAndUpdateWorkingAttribute()
   at Reflexil.Forms.EditCustomAttributeForm.ButUpdate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by sailro** [comment]
Can you craft a repro please ? So that I can see what is wrong

**Comment by sailro** [comment]
Ok I've found the issue
